apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: cr.metax-tech.com/public-ai-release/maca/sglang
    newTag: 0.5.12-maca.ai3.8.2.7-torch2.10-py312-ubuntu22.04-amd64
